# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-02 04:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portifolios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dadospessoais',
            options={'verbose_name': 'Dados Pessoais', 'verbose_name_plural': 'Dados Pessoais'},
        ),
    ]
