# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-02 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolios', '0002_auto_20180502_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadospessoais',
            name='cep',
            field=models.CharField(default=3, max_length=50, verbose_name='CEP'),
            preserve_default=False,
        ),
    ]
