# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-02 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolios', '0003_dadospessoais_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadospessoais',
            name='cep',
            field=models.CharField(max_length=50, verbose_name='Cep'),
        ),
    ]
