# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-02 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolios', '0004_auto_20180502_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadospessoais',
            name='data_nascimento',
            field=models.CharField(default='1 Janeiro 2000', max_length=255, verbose_name='Data Nascimento'),
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='github',
            field=models.CharField(default='http://github.com/SeuGit', max_length=100, verbose_name='GitHub'),
        ),
    ]
